# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Splash < Formula
  desc "Add color to your logs"
  homepage "https://github.com/joshi4/splash"
  version "0.6.0"
  license "MIT"

  on_macos do
    url "https://github.com/joshi4/splash/releases/download/v0.6.0/splash_darwin_all"
    sha256 "abcc9a3175b7ea4078ce68d977dd515c29607355ba3243c9b552495d4406d668"

    def install
      bin.install "splash"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/joshi4/splash/releases/download/v0.6.0/splash_linux_x86_64"
      sha256 "ea60bb0a9c5a3311d8bdf148c144339aca7f9a7def84a8eadea4398d32232b96"
      def install
        bin.install "splash"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/joshi4/splash/releases/download/v0.6.0/splash_linux_arm64"
      sha256 "623454f714f1b5fee72207acbef227d7f8f21eb876526eb8c9a4e054fe13160a"
      def install
        bin.install "splash"
      end
    end
  end

  test do
    system "#{bin}/splash", "version"
  end
end
